/*
 * wdt_program.c
 *
 * Created: 3/3/2025 9:34:11 PM
 *  Author: Ahmad abdullatif
 */
#include "std_types.h"
#include "bit_math.h"
#include "DIO_interface.h"
#include "wdt_interface.h"
#include "wdt_registers.h"


void WDT_voidEnable (u8 copy_u8TimeOut){
	switch(copy_u8TimeOut){
		case WDT_TIME_16_3_MS:
		CLEAR_BIT(WDTCR_REGISTER,WDP0_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP1_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_32_5_MS:
		SET_BIT(WDTCR_REGISTER,WDP0_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP1_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_65_MS:
		CLEAR_BIT(WDTCR_REGISTER,WDP0_BIT);
		SET_BIT(WDTCR_REGISTER,WDP1_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_0_13_S:
		SET_BIT(WDTCR_REGISTER,WDP0_BIT);
		SET_BIT(WDTCR_REGISTER,WDP1_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_0_26_S:
		CLEAR_BIT(WDTCR_REGISTER,WDP0_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP1_BIT);
		SET_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_0_52_S:
		SET_BIT(WDTCR_REGISTER,WDP0_BIT);
		CLEAR_BIT(WDTCR_REGISTER,WDP1_BIT);
		SET_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_1_S:
		CLEAR_BIT(WDTCR_REGISTER,WDP0_BIT);
		SET_BIT(WDTCR_REGISTER,WDP1_BIT);
		SET_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;
		
		case WDT_TIME_2_1_S:
		SET_BIT(WDTCR_REGISTER,WDP0_BIT);
		SET_BIT(WDTCR_REGISTER,WDP1_BIT);
		SET_BIT(WDTCR_REGISTER,WDP2_BIT);
		break;	
	}
	//enable WDT
	SET_BIT(WDTCR_REGISTER,WDE_BIT);
}
void WDT_voidDisable(){
	WDTCR_REGISTER |= 1<<WDE_BIT | 1<<WDTOE_BIT;
	WDTCR_REGISTER = 0;
}